/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostersRouteImport } from './routes/posters'
import { Route as PostersBannerRouteImport } from './routes/posters.banner'
import { Route as PostersSquareRouteImport } from './routes/posters.square'
import { Route as PostersStoryRouteImport } from './routes/posters.story'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostersRoute = PostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => rootRouteImport,
} as any)
const PostersBannerRoute = PostersBannerRouteImport.update({
  id: '/banner',
  path: '/banner',
  getParentRoute: () => PostersRoute,
} as any)
const PostersSquareRoute = PostersSquareRouteImport.update({
  id: '/square',
  path: '/square',
  getParentRoute: () => PostersRoute,
} as any)
const PostersStoryRoute = PostersStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => PostersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posters': typeof PostersRouteWithChildren
  '/posters/banner': typeof PostersBannerRoute
  '/posters/square': typeof PostersSquareRoute
  '/posters/story': typeof PostersStoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posters': typeof PostersRouteWithChildren
  '/posters/banner': typeof PostersBannerRoute
  '/posters/square': typeof PostersSquareRoute
  '/posters/story': typeof PostersStoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posters': typeof PostersRouteWithChildren
  '/posters/banner': typeof PostersBannerRoute
  '/posters/square': typeof PostersSquareRoute
  '/posters/story': typeof PostersStoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/posters' | '/posters/banner' | '/posters/square' | '/posters/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/posters' | '/posters/banner' | '/posters/square' | '/posters/story'
  id:
    | '__root__'
    | '/'
    | '/posters'
    | '/posters/banner'
    | '/posters/square'
    | '/posters/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostersRoute: typeof PostersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posters': {
      id: '/posters'
      path: '/posters'
      fullPath: '/posters'
      preLoaderRoute: typeof PostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posters/banner': {
      id: '/posters/banner'
      path: '/banner'
      fullPath: '/posters/banner'
      preLoaderRoute: typeof PostersBannerRouteImport
      parentRoute: typeof PostersRoute
    }
    '/posters/square': {
      id: '/posters/square'
      path: '/square'
      fullPath: '/posters/square'
      preLoaderRoute: typeof PostersSquareRouteImport
      parentRoute: typeof PostersRoute
    }
    '/posters/story': {
      id: '/posters/story'
      path: '/story'
      fullPath: '/posters/story'
      preLoaderRoute: typeof PostersStoryRouteImport
      parentRoute: typeof PostersRoute
    }
  }
}

interface PostersRouteChildren {
  PostersBannerRoute: typeof PostersBannerRoute
  PostersSquareRoute: typeof PostersSquareRoute
  PostersStoryRoute: typeof PostersStoryRoute
}

const PostersRouteChildren: PostersRouteChildren = {
  PostersBannerRoute: PostersBannerRoute,
  PostersSquareRoute: PostersSquareRoute,
  PostersStoryRoute: PostersStoryRoute,
}

const PostersRouteWithChildren =
  PostersRoute._addFileChildren(PostersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostersRoute: PostersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
